import {
  GiDrumKit,
  GiSandsOfTime,
  GiGuitarBassHead,
  GiPianoKeys,
  GiTrumpet,
  GiMetronome,
  GiHandBag,
  GiWaterDrop,
  GiGuitar,
} from 'react-icons/gi'
import { TbBellRinging2Filled } from 'react-icons/tb'
import { InstrumentPreset } from '../types'

export const DEFAULT_PRESETS: InstrumentPreset[] = [
  {
    id: 'kick',
    name: 'Kick',
    type: 'Drums',
    icon: GiDrumKit,
    accent: '#E24B4A',
    synth: 'MembraneSynth',
    note: 'C1',
    options: { pitchDecay: 0.05, octaves: 6 },
  },
  {
    id: 'snare',
    name: 'Snare',
    type: 'Drums',
    icon: GiSandsOfTime,
    accent: '#D85A30',
    synth: 'NoiseSynth',
    note: null,
    options: { noise: { type: 'white' }, envelope: { attack: 0.001, decay: 0.2, sustain: 0 } },
  },
  {
    id: 'hihat',
    name: 'Hi-Hat',
    type: 'Percussion',
    icon: GiMetronome,
    accent: '#BA7517',
    synth: 'MetalSynth',
    note: 'C6',
    options: {
      frequency: 400,
      envelope: { attack: 0.001, decay: 0.1, release: 0.01 },
      harmonicity: 5.1,
      modulationIndex: 32,
      resonance: 4000,
      octaves: 1.5,
    },
  },
  {
    id: 'bass',
    name: 'Bass',
    type: 'Bass',
    icon: GiGuitarBassHead,
    accent: '#1D9E75',
    synth: 'Synth',
    note: 'C2',
    options: {
      oscillator: { type: 'square' },
      envelope: { attack: 0.01, decay: 0.3, sustain: 0.4, release: 0.5 },
    },
  },
  {
    id: 'chord',
    name: 'Chord',
    type: 'Harmony',
    icon: GiPianoKeys,
    accent: '#7F77DD',
    synth: 'PolySynth',
    note: ['C3', 'E3', 'G3'],
    options: {},
  },
  {
    id: 'lead',
    name: 'Lead',
    type: 'Melody',
    icon: GiTrumpet,
    accent: '#D4537E',
    synth: 'Synth',
    note: 'C4',
    options: {
      oscillator: { type: 'sawtooth' },
      envelope: { attack: 0.02, decay: 0.1, sustain: 0.5, release: 0.5 },
    },
  },
]

export const EXTRA_PRESETS: InstrumentPreset[] = [
  {
    id: 'cowbell',
    name: 'Cowbell',
    type: 'Percussion',
    icon: TbBellRinging2Filled,
    accent: '#BA7517',
    synth: 'MetalSynth',
    note: 'G4',
    options: {
      frequency: 566,
      envelope: { attack: 0.001, decay: 0.4, release: 0.1 },
      harmonicity: 5.1,
      modulationIndex: 16,
      resonance: 3200,
      octaves: 0.5,
    },
  },
  {
    id: 'clap',
    name: 'Clap',
    type: 'Drums',
    icon: GiHandBag,
    accent: '#D85A30',
    synth: 'NoiseSynth',
    note: null,
    options: { noise: { type: 'pink' }, envelope: { attack: 0.005, decay: 0.1, sustain: 0 } },
  },
  {
    id: 'pad',
    name: 'Pad',
    type: 'Atmosphere',
    icon: GiWaterDrop,
    accent: '#378ADD',
    synth: 'PolySynth',
    note: ['C2', 'G2'],
    options: {},
  },
  {
    id: 'pluck',
    name: 'Pluck',
    type: 'Melody',
    icon: GiGuitar,
    accent: '#639922',
    synth: 'PluckSynth',
    note: 'E4',
    options: {},
  },
]

export const ALL_PRESETS = [...DEFAULT_PRESETS, ...EXTRA_PRESETS]